### ISSUE TITLE
Put fan speed back to preferred level

### ISSUE THREAD

**Issue by dalcon007** [NoLooseEnds/Scripts#5]
This is working great so far. The only issue is that fans don't go back down to the preferred level after the temp has decreased. I feel like this can be achieved with a reverse if statement, something like:
if [[ $TEMP < $MAXTEMP ]];

Do you think this would work? Sorry for posting as an issue, I had nowhere else to post this!

**Comment by Tucker2015** [comment]
It can be achieved I have it in my script but not at my server right now.  I will post it soon if you don’t work it out

**Comment by dalcon007** [comment]
I'll give it a try in the mean time. Thanks!

**Comment by NoLooseEnds** [comment]
It's possible as stated by @Tucker2015. :)

I just don't want it to go back and forth, and wanted to start it manually. If it triggers it's usually a reason for it. Also, since I have set the interval to every five minutes, I guess it could potentially not be that great for the lifespan of the system.

I'm leaving this open for a while. Appreciate if you post the solution here. :)

**Comment by NoLooseEnds** [comment]
.
